name: Solve Issue with ChatGPT

on:
  issue_comment:
    types:
      - created

jobs:
  solve_issue:
    if: startsWith(github.event.comment.body, '/solve')
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run AIPR Action
        uses: cameronking4/AIPR@v1.0.0
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_tokens: 1500                # Adjust if necessary
          openai_model: gpt-4o              # Default model from action.yml
          file_chunks: 5                    # Adjust based on your requirements
          target_branch: main
